[package]
name = "gpui-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.42.0"
gpui = { git = "https://github.com/zed-industries/zed" }
unicode-segmentation = "1.12.0"
smallvec = "1.13.2"
